project:
  type: book
  output-dir: "../docs"

## Overall settings
book:
  title: "Bias in Facial Classification ML Models"
  author:
    - "Patrick Connelly"
    - "Grace Cooper"
    - "Bhavana Jonnalagadda"
    - "Carl Klein"
    - "Piya (Leo) Ngamkam"
    - "Dhairya Veera"
  chapters:
    - index.qmd
    - intro.qmd
    - data.qmd
    - methods.qmd
    - results.qmd
    - conclusions.qmd
    - references.qmd
  downloads: [pdf]
  references: references.bib # Unsure if needed
  output-file: STAT_5000_Final_Report # PDF filename
  cover-image: "images/cover.png"
  repo-url: "https://github.com/CUBoulder-DS/5301-5000-Final-Report"
  page-navigation: true
  navbar:
    pinned: true
  date: today

bibliography: references.bib
nocite: |
  @*

## Controls for each output format
format:
  html:
    theme: flatly
    page-layout: full
    smooth-scroll: true
    number-sections: true
    citations-hover: true
    grid:
      body-width: 1000px
      sidebar-width: 150px
  pdf:
    documentclass: scrreprt
    number-depth: 4
    toc: true
    geometry:
      - margin=0.5in
    link-citations: true
    header-includes: # dont need?
      - \usepackage{float}
      - \floatplacement{table}{H}
      - \floatplacement{image}{H}
    hyperrefoptions:
      - linktoc=all
    latex-output-dir: "../docs"

## Extra settings
execute:
  echo: false # Don't include code in the report
  freeze: false # Not useful when rendering across multiple users
  warning: false
  error: false

## PDF creation settings
latex-clean: true # delete latex files after rendering
latex-auto-mk: true
latex-auto-install: true
