# Simple workflow for deploying static content to GitHub Pages
name: Convert the project notebook into a github-pages site

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "requirements.txt"
      # The only step/code that matters/was customized
      - name: Run the html conversion creation
        run: |
             jupyter nbconvert --to html --output-dir="docs/" 5301_Final_Report.ipynb
      - name: Commit file changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate html for website from notebook
          file_pattern: 'docs/'
          push_options: '--force'
          add_options: '-u'
